# Site settings
title: Donguk Seo
baseurl: ""
url: "https://seodu.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Donguk Seo
  desc: Master degree candidate
  email: dongukseo@kaist.ac.kr
  selfie: assets/img/sdu_profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: SeoDU
  google_plus:
  instagram:
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
